### ISSUE TITLE
Crash on retweet

### ISSUE THREAD

**Issue by jjardel** [jjardel/distractingdonald#7]
app.py crashes with following error log.

> 2017-02-06 16:32:25,037 - model.src._stream_processor - 101 -  INFO - Found a tweet!
The failing @nytimes writes total fiction concerning me. They have gotten it wrong for two years, and now are making up stories &amp; sources!
2017-02-06 16:32:25,037 - model.src._stream_processor - 110 -  INFO - Loading serialized model
2017-02-06 16:32:25,404 - model.src._stream_processor - 61 -  INFO - Twitter credentials loaded
2017-02-06 16:32:25,495 - model.src._stream_processor - 158 -  INFO - Probability this was a POTUS tweet is 72.62%
2017-02-06 16:32:25,567 - model.src._stream_processor - 158 -  INFO - Probability this was a POTUS tweet is 72.62%
2017-02-06 16:32:25,568 - tweepy.binder - 107 -  INFO - PARAMS: {'status': b'There is a 73% chance that this tweet was written by POTUS https://twitter.com/realDona
ldTrump/status/828642511698669569'}
2017-02-06 16:32:25,569 - requests_oauthlib.oauth1_auth - 63 -  DEBUG - Signing request <PreparedRequest [POST]> using client <Client decoding=None, signature_type=
AUTH_HEADER, client_key=sXnweIGKcFrpvF3VwJhFWQgzH, resource_owner_secret=****, rsa_key=None, timestamp=None, encoding=utf-8, verifier=None, nonce=None, client_secre
t=****, realm=None, signature_method=HMAC-SHA1, callback_uri=None, resource_owner_key=****>
2017-02-06 16:32:25,569 - requests_oauthlib.oauth1_auth - 75 -  DEBUG - Including body in call to sign: False
2017-02-06 16:32:25,569 - oauthlib.oauth1.rfc5849 - 134 -  DEBUG - Collected params: [('status', 'There is a 73% chance that this tweet was written by POTUS https:/
/twitter.com/realDonaldTrump/status/828642511698669569'), ('oauth_signature_method', 'HMAC-SHA1'), ('oauth_consumer_key', '****'), ('oauth_time
stamp', '1486398745'), ('oauth_nonce', '****'), ('oauth_version', '1.0'), ('oauth_token', '****')]
2017-02-06 16:32:25,570 - oauthlib.oauth1.rfc5849 - 139 -  DEBUG - Normalized params: oauth_consumer_key=****&oauth_nonce=****&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1486398745&oauth_token=****&oauth_version=1.0&status=There%
20is%20a%2073%25%20chance%20that%20this%20tweet%20was%20written%20by%20POTUS%20https%3A%2F%2Ftwitter.com%2FrealDonaldTrump%2Fstatus%2F828642511698669569
2017-02-06 16:32:25,570 - oauthlib.oauth1.rfc5849 - 140 -  DEBUG - Normalized URI: https://api.twitter.com/1.1/statuses/update.json
2017-02-06 16:32:25,570 - oauthlib.oauth1.rfc5849 - 145 -  DEBUG - Base signing string: POST&https%3A%2F%2Fapi.twitter.com%2F1.1%2Fstatuses%2Fupdate.json&oauth_consumer_key%****%26oauth_nonce%****%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1486398745%26oauth_token%****%26oauth_version%3D1.0%26status%3DThere%2520is%2520a%252073%2525%2520chance%2520that%2520this%2520tweet%2520wapvF3VwJhFWQgzH", oauth_token=****, oauth_signature=****}
2017-02-06 16:32:25,571 - requests_oauthlib.oauth1_auth - 94 -  DEBUG - Updated body: None
2017-02-06 16:32:25,572 - requests.packages.urllib3.connectionpool - 818 -  DEBUG - Starting new HTTPS connection (1): api.twitter.com
2017-02-06 16:32:25,926 - requests.packages.urllib3.connectionpool - 395 -  DEBUG - https://api.twitter.com:443 "POST /1.1/statuses/update.json?status=There+is+a+73%25+chance+that+this+tweet+was+written+by+POTUS+https%3A%2F%2Ftwitter.com%2FrealDonaldTrump%2Fstatus%2F828642511698669569 HTTP/1.1" 200 5053
2017-02-06 16:32:25,928 - model.src._stream_processor - 176 -  INFO - Retweeted tweet ID 828642511698669569
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/jjardel/anaconda3/envs/python3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/jjardel/anaconda3/envs/python3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jjardel/anaconda3/envs/python3/lib/python3.5/site-packages/tweepy/streaming.py", line 294, in _run
    raise exception
  File "/home/jjardel/anaconda3/envs/python3/lib/python3.5/site-packages/tweepy/streaming.py", line 263, in _run
    self._read_loop(resp)
  File "/home/jjardel/anaconda3/envs/python3/lib/python3.5/site-packages/tweepy/streaming.py", line 313, in _read_loop
    line = buf.read_line().strip()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by jjardel** [comment]
The last timestamp of the logfile was Feb  6 22:47, so the failure seems unrelated to the retweet which happened at 16:32.
